# .github/workflows/cd.yml

name: Continuous Delivery
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches: ["master", "release/*"]

jobs:
  staging:
    name: Deploy Staging
    if: github.ref != 'refs/heads/master' && startsWith(github.ref, 'refs/heads/release/')
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: ${{ steps.vercel.outputs.url }}
    steps:
      - name: Checkout code from GitHub
        uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install --global vercel@canary

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=development --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} > deployment-url.txt

      - name: Set output URL
        id: vercel
        run: echo "url=$(cat deployment-url.txt)" >> $GITHUB_OUTPUT

  production:
    name: Deploy Production
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ steps.vercel.outputs.url }}
    # needs: [staging]
    steps:
      - run: echo ${{ github.ref }}
      - name: Checkout code from GitHub
        uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install --global vercel@canary

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }} > deployment-url.txt

      - name: Set output URL
        id: vercel
        run: echo "url=$(cat deployment-url.txt)" >> $GITHUB_OUTPUT
