# .github/workflows/ci.yml

name: Continuous Integration
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches: ["development"]
  pull_request:
    branches: ["development"]

jobs:
  linttest:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm install

      - name: Run linter to check code style and formatting
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Run build
        run: npm run build

  preview:
    name: Deploy Preview
    if: github.event_name == 'pull_request'
    needs: [linttest]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from GitHub
        uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install --global vercel@canary

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} > deployment-url.txt

      - name: Set output URL
        id: vercel
        run: echo "url=$(cat deployment-url.txt)" >> $GITHUB_OUTPUT

      - name: Comment on Pull Request
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Preview URL: ${{ steps.vercel.outputs.url }}
